### ISSUE TITLE
Able to extract data from FunOrb/Arcanists?

### ISSUE THREAD

**Issue by Chdata** [villermen/runescape-cache-tools#17]
It's technically still possible to play the game and I seem to still have all spellbooks fully unlocked.

Arcanists doesn't seem to produce the same cache folders however.

**Comment by Villermen** [comment]
I have no idea if they use the same protocols. They are not developed by the same team and might use an entirely different strategy for storing cache (if they do at all). I have no experience whatsoever with FunOrb, nor will I try to get it, so someone else is probably more suited to dive into this.

**Comment by villermen** [comment]
I'm closing this unless someone can confirm to me that Arcanists' cache format is similar to RuneScape's.
