### ISSUE TITLE
Lossless concatenation into OGG file format

### ISSUE THREAD

**Issue by villermen** [villermen/runescape-cache-tools#36]
Theoretically easy: Concatenate the files into one file, or concatenate all Vorbis packets into one stream and fix the granule positions of the generated pages.

Practically not so much. The audio chunks from the cache are different. When the packets are concatenated, silence appears at the end of every chunk that isn't there when just reading one chunk on its own. This can be made visible by converting to a lossless format from FFmpeg, and opening both files in Audacity. FFmpeg in particular tries to demux instead of decode the audio for as long as possible, thus exposing this issue the easiest. The extra silence is arbitrary in length, so my best guess is that it fills out space that is reserved for the length of the chunk or a rounding error or something. I have not been able to remove the silence without re-encoding the file.

**Comment by villermen** [comment]
It might be possible that this error is only contained in the last packet of a chunk's stream. If that is the case the files can be fixed without re-encoding, but that requires [libogg-sharp](https://github.com/villermen/libogg-sharp) to include libvorbis for reading out granule positions of the remaining packets. Takes a lot of work, and this issue has become a pretty low priority to me.

**Comment by Locitao** [comment]
Is the silence only detectable by opening the file in Audacity? If not, I might have an idea, without needing to re-encode the files.

1. Concatenate the files.
2. Detect if and where there is a silence.
3. Trim away the silence from the concatenated file.

I presume FFmpeg or a similar program has a way to trim an audio file; if this isn't the case this idea becomes a bit more difficult.

**Comment by villermen** [comment]
@Locitao The silence is easily detectable and removable. The issue lies in the fact that any adjustments to the audio data except from removing or adding full OGG packets/pages would require the audio to be re-encoded, losing precious quality or increasing filesize.

**Comment by Locitao** [comment]
@villermen I've found the following, if you add "-acodec copy" to the command for cutting part of an audio file, it simply copies it to a new file without re-encoding it. Perhaps it'd be possible to cut the part before the silence out to a new file, cut the part after the silence out to a new file, and then concatenate these two new files?

More information (for the command I mentioned above, see the last comment under the answer): http://stackoverflow.com/a/7945753

**Comment by villermen** [comment]
Theoretically this is impossible, because the lowest level you can go without re-encoding is packet-level. I've still experimented with this and have done concatenation with FFmpeg with outpoints like `ffmpeg -i concat.txt -c copy concat.ogg` where concat.txt contained something like:

```
file 15768.ogg
outpoint 3.778
file 15769.ogg
outpoint 3.895
```

This gives me a file with only one sample of silence ("unnoticable") and approximately the same duration, but the second sample doesn't line up with where it should've been. The silence occurs on the part that used to contain audio data. This means you either lose audio or add silence when using FFmpeg this way. In addition you also need to know precisely how long the track is and how long the silence would be (which is almost impossible without specialist tools).

If it is even possible this needs a specialist solution as I mentioned [earlier](https://github.com/villermen/runescape-cache-tools/issues/36#issuecomment-265686454). That would allow fine-grained control over how many packets or pages to leave out, instead of working with timestamps.

**Comment by villermen** [comment]
¯\\\_(ツ)\_\/¯
