### ISSUE TITLE
pre-compiled exe closes upon opening

### ISSUE THREAD

**Issue by pxssy** [villermen/runescape-cache-tools#50]
there's some writing before it closes itself. it happens really quickly and i can't read anything

**Comment by villermen** [comment]
rsct.exe is not a graphical tool. It is a command-line program that must be run from an open terminal window.

If you're not familiar with the command-line give [this page](https://www.davidbaumgold.com/tutorials/command-line/) a read.

I'm getting a lot of emails about this, so I'll probably create a mention in the README for this. Leaving this issue open until I've done this. Feel free to ask any remaining questions regarding the tool.

**Comment by pxssy** [comment]
Okay i got babun, but i'm not sure how to extract files off the cache.

Do i do rsct --extract 'path' or what

I'm sorry im not really tech savy

**Comment by villermen** [comment]
You can (and must) combine arguments to make the program do something useful. For example, `rsct.exe --extract --index 20` will extract all files in index 20 from the default cache location (java cache) to the output directory. You can download files directly from Jagex's servers by adding `--download`, and can set the output directory to C:\SomeOutputDirectory by adding `--output-directory "C:\SomeOutputDirectory`.

**Comment by villermen** [comment]
Also, babun? Never heard of it. Is it some kind of terminal? As that page showed you can open a terminal by simply pressing <kbd>Windows</kbd> + <kbd>R</kbd> and running `cmd`.

**Comment by mini890** [comment]
Babun is a linux-like terminal just a bit like cygwin or mingw

**Comment by villermen** [comment]
Now [mentioned in the readme](https://github.com/villermen/runescape-cache-tools/blob/master/README.md#the-program-opens-and-closes-right-after), with a followup issue #62.
