### ISSUE TITLE
App Crashes On Opening

### ISSUE THREAD

**Issue by devKepler** [villermen/runescape-cache-tools#61]
I downloaded the latest zip, unzipped it, ran the program. The CMD flashes and disappears and the program exists. Same happens when trying to run as administrator

**Comment by villermen** [comment]
Please see #50. You should run the program as a command-line executable (from the terminal).

**Comment by villermen** [comment]
[Now also noted in the readme file](https://github.com/villermen/runescape-cache-tools/blob/master/README.md#the-program-opens-and-closes-right-after).

**Comment by devKepler** [comment]
@villermen is there a way to extract models and maps if i want that too?

**Comment by villermen** [comment]
Yes, by specifying the right indexes to extract. E.g.: `rsct.exe --extract --index 15`. Where 15 is the number of the index you want to extract (you can replace this with a range like 13-15,17 to extract indexes 13, 14, 15 and 17).

For a list of indexes and what they should contain see [this file](https://github.com/villermen/runescape-cache-tools/blob/master/RuneScapeCacheTools/Cache/Index.cs).

**Comment by devKepler** [comment]
You're a saint ty

**Comment by villermen** [comment]
You're welcome =)
