### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by Toshiba1127** [villermen/runescape-cache-tools#72]
Can you add an option to extract sound effects from cache? I wanna extract some sound effects like jingles and any that are not part of soundtrack

**Comment by villermen** [comment]
@Toshiba1127 You should be able to extract sound effects using `rsct.exe audio --download --scrape=14/1-1000` (to try to combine files 1-1000 in the sound effects index). This is a tedious process and there are tons of sound effects, but this should get you started. You can't just specify `rsct.exe audio --download --scrape=14` right now to target all sound effects as some high number files will throw an error.

**Comment by Toshiba1127** [comment]
ok, sad they are unnamed

**Comment by villermen** [comment]
Nothing is I'm afraid. The only reason I'm able to get the music track names is because I've found where they are stored. The sound effects are not shown by name in-game so they are probably not stored either.
