### ISSUE TITLE
Please provide a way to losslessly concatenate the ogg vorbis chunks

### ISSUE THREAD

**Issue by josch** [villermen/runescape-cache-tools#8]
Currently, when concatenating the individual ogg vorbis chunks that make a music track, sox is used. This will lead to the audio stream being re-encoded into ogg vorbis. This in turn will lead to a tiny loss in quality. Thus, this is not a good way to archive the runescape music as one will not end up with the truly original music but a slightly modified version. There are two solutions:
1. provide an alternative method where the ogg vorbis chunks are just concatenated into a single file by writing them to the out file one after another. The ogg format supports this simple concatenation of files and most players support it, too.
2. provide a way to let sox not save the output in ogg vorbis format but in a lossless format like flac. This will result in bigger files than with the first option but is useful for players which do not support concatenated ogg vorbis files (windows media player for example).

Having both options would be useful, too.

**Comment by Villermen** [comment]
The first thing I did was try to concatenate the ogg files together using the chunks only. This did not work as jagex has decided to store every chunk as it's own ogg file (with header and all), so meta, like chunk length would be screwed up and would not compute. Right now sox will not change the quality of the files in any way as long as they are the same bitrate it will just keep them at the quality they are (given the option I have inserted). I do agree that this is sort of a hack, but I couldn't figure it out myself.

I'll definitely implement the second option though.

**Comment by josch** [comment]
No, concatenating individual ogg files (together with their header) *does* work. At least it is supposed to work according to the ogg vorbis spec. If your player cannot do it, then your player does not fully implement the ogg vorbis format.

But if you try to play such a concatenated file with a player like mplayer, ffmpeg or vlc, then you will hear the full track without noticing that they were concatenated.

There are two downsides of this approach:

 - players supporting this would only see the lengths of the individual chunks and not the length of the whole file
 - some players which do not implement the ogg spec will only play the first chunk

About the current encoding to ogg: this *will* result in a loss in quality. That you set the same encoding quality as was used to encode the input does not mean that the conversion is lossless. Some information will be lost after the re-encoding step. That they are the same bitrate has nothing to do with it.

**Comment by Villermen** [comment]
Still though, I have added all the file's chunks together in many ways and tried to play the resulting file in VLC without success. I have spent too much time on trying to get that to work to think of trying to go there again.

**Comment by josch** [comment]
I found a solution: ffmpeg can do it.

It works like the following:

 1. prepare a file `inputs.txt` listing the files to concatenate with this format:

```
file 'rscachetool/out/40/39925.ogg'
file 'rscachetool/out/40/39926.ogg'
file 'rscachetool/out/40/39927.ogg'
```

 2. call ffmpeg like this:

```
ffmpeg -f concat -i inputs.txt -c copy out.ogg
```

I verified can confirm that the vorbis packets of the input are copied 1:1 to the output. You can easily make sure yourself by using a hex editor. You will see that the binary from the input files exactly appears in the output (minus the ogg headers which are necessarily different because of the different file sizes).

**Comment by Villermen** [comment]
Concatenating this way will cause the sound to contain holes. Try out (this version of the tool)[https://villermen.com/dump/rscachetool_ffmpeg.zip] (Release binary) I created and compare it's output to the previous one and you'll probably notice it. FFmpeg gives warnings about this too, but I have no idea what could be causing it.

**Comment by josch** [comment]
I cannot hear any holes when I use ffmpeg to do the concatenation.

Maybe you used an older version? I'm using ffmpeg 2.5.

Or maybe whether or not there are holes depends on the input file. Can you tell me a sound track where you definitely hear holes using this method so that I can try reproducing the effect you see?

I also cannot see the ffmpeg warnings that you see when concatenating the way I described. On my system, ffmpeg 2.5 is concatenating the files without complaining.

I cannot try the version of the tool you linked because I don't run windows.

**Comment by Villermen** [comment]
The holes are present in all files to me and they're easily noticable.
Here's a comparison: [5233._comparison.zip](
https://villermen.com/dump/5233_comparison.zip). At around 3 seconds the
first chunk ends and that's where the first hole can be noticed.

Errors that FFmpeg spouts are similar to this:
![Console](http://puu.sh/eF8Vh/2615f45115.png)

I'll try to test some more to see if it's to do with the ~index.ogg (which
is most unreliable in my eyes), but apart from that I do not know. The
FFmpeg version I'm using is the latest recommended build downloaded from
their site yesterday (2015-01-15 git-cd960c8 32-bit static).

**Comment by Villermen** [comment]
The holes are present in all files to me and they're easily noticable. Here's a comparison: [5233._comparison.zip](https://villermen.com/dump/5233_comparison.zip). At around 3 seconds the
first chunk ends and that's where the first hole can be noticed.

Errors that FFmpeg spouts are similar to this:
![Console](http://puu.sh/eF8Vh/2615f45115.png)

I'll try to test some more to see if it's to do with the ~index.ogg (which is most unreliable in my eyes), but apart from that I do not know. The FFmpeg version I'm using is the latest recommended build downloaded from their site yesterday (2015-01-15 git-cd960c8 32-bit static).

**Comment by josch** [comment]
I think I now know the source of the confusion.

It seems to depend on the input file whether or not there is a tiny "gap" or not and whether or not ffmpeg will show above message.

For example try combining 9848 with ffmpeg. I didn't get any warning and also cannot hear the gap.

Also notice that some chuncks are 3.918s long, others are 7.836s so one has to wait a bit longer to hear the gap.

Nevertheless, since some file do have this problem when combined with ffmpeg, this method indeed seems to be flawed.

It seems that in the end the only way to properly archive the sound will be by encoding into a lossless format like wav or flac... :(

**Comment by josch** [comment]
Another amandment: in case anybody ever stumbles over them and posts a solution, I asked for a program concatenating audio files without re-encoding on superuser: http://superuser.com/questions/864911/lossless-concatenation-of-ogg-vorbis-files

Since such a program didn't seem to exist I tried to write my own by just concatenating the raw vorbis packets but that still sometimes results in tiny gaps: http://stackoverflow.com/questions/27980960/how-to-lossless-concatenate-ogg-vorbis-files

**Comment by Villermen** [comment]
That should fix the lossless part just fine. Still though, lossless concatenation into ogg format would be even more awesome. (I'll definitely keep an eye on your SO question.)

**Comment by villermen** [comment]
I think the problem laid with the extraction progress. I've run a small test on [my new codebase](https://github.com/villermen/runescape-cache-tools/tree/feature/proper-cache-implementation) on one full soundtrack with oggCat, which concatenates losslessly, and have noticed no errors. If this is the same for every soundtrack I'm on my way to fixing this. About time right?

**Comment by villermen** [comment]
Ok, so out of 1126 tracks, 5 tracks failed to combine with oggCat and the new cache system. Problem is that if you run the same command line arguments from a regular terminal oggCat will close fine (in the application it will just hang indefinitely), and still produce a mangled result. I can't be sure about all the other tracks now, so oggCat can scram. Mentioning @Locitao here, because he might be our Jesus on this one (https://github.com/Locitao/ogg-concatenation).

**Comment by Locitao** [comment]
Working on it, but can't promise anything. Any idea what's different in those 5 files that differs from the others?

**Comment by villermen** [comment]
Not a clue, but the resulting track (or as far as oggCat can get with them) seem to be either full tracks with specific audio data missing, or parts of full tracks. For some reason they sound like proper songs still. In [this zip](https://viller.men/dump/oggcatpls.7z) are the comparisons of the output files between oggCat and SoX. I can't easily obtain the source tracks of the output files, but can given some work if you need them.

Especially note the difference between the two Yk'Lagor the Thunderous files, they are the strangest of the bunch.

At the end of the day, it might just be that oggCat is stupid, so the best approach would probably be to get a working program and then checking what is different with these files after it can tell that.

**Comment by villermen** [comment]
Ok, I've done some educated guessing, and the thing that's different about the tracks is that they are the only ones with multiple defined names. 

https://gist.github.com/villermen/e3db033dd61bb07ec5f5587a0e9c3d8a

Running this program on the latest source will reveal that there are just these 5 track names that have multiple file ids linking from them. Jagex probably failed at a point in putting these tracks in the cache, and didn't bother to get them out? My job now is of course to select the one that is actually used in the game, and not the corrupted one.

**Comment by villermen** [comment]
The 5 track thing is fixed in 31214a7cb6f9a50aea6f6c3adff600b81e2e02fa. I just export all of them with a suffix.

**Comment by twrightsman** [comment]
Just to clarify, oggCat is working as expected and by handling the tracks with multiple files each in your code you were able to solve this issue? Need to know for the NXT cache, in case they kept the same corruption

**Comment by villermen** [comment]
Yes, the corruption is gone. It was due to some bytes at the end of the OGG files that did not belong there. (Meaning I decoded them wrong.) The NXT files should work just as well.

oggCat re-encodes the audio, meaning the lossy data gets even lossier. By lossless we mean no more loss than already in the files. OGG allows this by straight up concatenating the files (e.g for streams), but then the metadata will be wrong. I want the best of both worlds, but oggCat will do for now.

**Comment by twrightsman** [comment]
I am planning on writing a pure python ogg concatenation module as part of the python cache tools because I can't find a decent ogg concat module. I'd also prefer to keep the code self-contained and not rely on third-party binaries like oggCat; it shouldn't be too bad, I've been reading the Ogg and Vorbis specs so I will be able to figure out how to recalculate metadata after concatenation [ this always assumes I find the time, of course ;) ]

**Comment by villermen** [comment]
I'm back with some news. I've done a lot of research and experimentation since the last message, and I've concluded that lossless concatenation is not possible for RuneScape's soundtrack. Other OGG files can be perfectly concatenated, but there's something different about the files in the cache. When they are joined by just concatenating the files or the low-level underlying packets (https://github.com/villermen/libogg-sharp) their PCM data is completed in between, leading to the small void in between audio files.

![concatenated cache files](https://cloud.githubusercontent.com/assets/1106303/20971729/d1addcd0-bc92-11e6-8b5a-13c1a05e11bc.png)

If this were fixable I would've delved even deeper to fix it, but in order to modify the raw packet data re-encoding has to happen. As it stands the only way to concatenate them into one file smoothly is by re-encoding. I'm going to abandon the idea that this is possible, and go back to using FFmpeg for concatenation, with the option of saving the sounds as FLAC for audiophiles. In the past I've used SoX and oggCat for concatenation, but FFmpeg is more stable and runs on a wider range of hardware.

I'm done with this matter, but the issue can be reopened if someone experiences a revelation.

**Comment by villermen** [comment]
Aaaand we're back opened... Even when re-encoding using FFmpeg there are these silent gaps. I **have** to fix this.

**Comment by josch** [comment]
I've used sox with success to concatenate the files without these gaps. The sox `--combine` command has also been there since ages, so I don't know what you mean that ffmpeg is "more stable". Due to the whole kaboodle with the avconv fork, you could even argue that ffmpeg is more fragile. Sox also seems to run on all major operating systems. Which OS are you missing?

Of course, if you manage to fix the problem with ffmpeg, I'm also interested in seeing your solution. :)

**Comment by villermen** [comment]
I am a fan of FFmpeg as I use it for other trivial things as well (including rendering the files to video's for YouTube). I thought I could easily get it to work if I just re-encoded it. You are right in that SoX is more reliable for these files. I just can't stand that I am now pretty much a master of concatenating arbitrary OGG files, but still can't seem to make this work. I want to figure out what is wrong with these files for them to turn up right in any audio editing program, but not when concatenated.

**Comment by josch** [comment]
I totally feel your pain. You already spent tons of effort on trying to *somehow* get these ogg streams concatenated without these nasty gaps. I hope you figure out how to do this with ffmpeg without too much hassle. :)

**Comment by villermen** [comment]
FLAC, Good enough :angry: ce3f76ab6b373c3f2f3e71b33b0bd6a1886ebfb5
